<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Contact Message</title>
</head>

<body style="margin: 0; padding: 0; font-family: 'Arial', sans-serif; background-color: #f7f7f7; color: #333;">
    <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #f7f7f7; padding: 40px 0;">
        <tr>
            <td align="center">
                <table width="600" cellpadding="0" cellspacing="0"
                    style="background-color: #ffffff; border-radius: 10px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.1);">

                    <!-- Header -->
                    <tr>
                        <td align="center" style="background-color: #e63946; padding: 20px;">
                            <h2 style="color: #ffffff; margin: 0; font-size: 22px; letter-spacing: 1px;">
                                📩 New Contact Message
                            </h2>
                        </td>
                    </tr>

                    <!-- Body -->
                    <tr>
                        <td style="padding: 30px;">
                            <p style="font-size: 16px; margin-bottom: 20px;">
                                You have received a new inquiry through your website contact form.
                            </p>

                            <table width="100%" cellpadding="5" cellspacing="0" style="font-size: 15px;">
                                <tr>
                                    <td width="30%" style="font-weight: bold;">👤 Name:</td>
                                    <td><?php echo new \Illuminate\Support\EncodedHtmlString($data['name']); ?></td>
                                </tr>
                                <tr>
                                    <td width="30%" style="font-weight: bold;">📧 Email:</td>
                                    <td><?php echo new \Illuminate\Support\EncodedHtmlString($data['email']); ?></td>
                                </tr>
                                <tr>
                                    <td width="30%" style="font-weight: bold;">📞 Phone:</td>
                                    <td><?php echo new \Illuminate\Support\EncodedHtmlString($data['phone']); ?></td>
                                </tr>
                                <tr>
                                    <td width="30%" style="font-weight: bold;">🧾 Service:</td>
                                    <td><?php echo new \Illuminate\Support\EncodedHtmlString($data['subject'] ?? $data['service'] ?? '-'); ?></td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <!-- Footer -->
                    <tr>
                        <td align="center" style="background-color: #fafafa; padding: 15px; font-size: 13px; color: #999;">
                            This email was automatically generated by your website contact form.<br>
                            <strong>© <?php echo new \Illuminate\Support\EncodedHtmlString(date('Y')); ?> <?php echo new \Illuminate\Support\EncodedHtmlString(config('app.name')); ?></strong>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>

</html>
<?php /**PATH C:\xampp\htdocs\digital_marketing_4website_from_anumam_with_backend\resources\views/emails/inquiry.blade.php ENDPATH**/ ?>